Repository dnd-side-project/dnd-13th-9-backend, pull requests merged in 2025-08, with the labels that each got.

#7 feat : #5 spotless 적용
  build.gradle
  src/main/java/com/example/dnd_13th_9_be/Dnd13th9BeApplication.java
  src/main/java/com/example/dnd_13th_9_be/health/presentation/HealthController.java
  src/main/java/com/example/dnd_13th_9_be/user/persistence/UserEntity.java
  src/main/java/com/example/dnd_13th_9_be/user/persistence/UserRepositoryImpl.java
  src/main/java/com/example/dnd_13th_9_be/user/presentation/UserController.java
  src/test/java/com/example/dnd_13th_9_be/Dnd13th9BeApplicationTests.java
  src/test/java/com/example/dnd_13th_9_be/health/presentation/HealthControllerTest.java
Labels: CHORE

#14 feat: #13 프론트 localhost에서 호출시 CORS 가능하도록 추가
  src/main/java/com/example/dnd_13th_9_be/config/WebConfig.java
Labels: FEAT

#15 chore: #9 QueryDSL 설정
  .gitignore
  build.gradle
  src/main/java/com/example/dnd_13th_9_be/config/QuerydslConfig.java
Labels: CHORE

#20 [CHORE] common api response global exception
  build.gradle
  src/main/java/com/example/dnd_13th_9_be/config/OpenApiConfig.java
  src/main/java/com/example/dnd_13th_9_be/global/error/BusinessException.java
  src/main/java/com/example/dnd_13th_9_be/global/error/ErrorCode.java
  src/main/java/com/example/dnd_13th_9_be/global/error/GlobalExceptionHandler.java
  src/main/java/com/example/dnd_13th_9_be/global/response/ApiResponse.java
  src/main/java/com/example/dnd_13th_9_be/global/response/ResponseCode.java
  src/main/java/com/example/dnd_13th_9_be/global/response/SuccessCode.java
  src/main/resources/application.yml
Labels: CHORE

#22 [FEAT] #21 계획, 폴더 CRUD API
  src/main/java/com/example/dnd_13th_9_be/folder/application/FolderService.java
  src/main/java/com/example/dnd_13th_9_be/folder/application/dto/FolderDetailResult.java
  src/main/java/com/example/dnd_13th_9_be/folder/application/dto/FolderSummaryResult.java
  src/main/java/com/example/dnd_13th_9_be/folder/application/port/FolderCommandPort.java
  src/main/java/com/example/dnd_13th_9_be/folder/application/port/FolderQueryPort.java
  src/main/java/com/example/dnd_13th_9_be/folder/application/port/PlanAccessPort.java
  src/main/java/com/example/dnd_13th_9_be/folder/persistence/FolderEntity.java
  src/main/java/com/example/dnd_13th_9_be/folder/persistence/FolderRepository.java
  src/main/java/com/example/dnd_13th_9_be/folder/persistence/FolderRepositoryCustom.java
  src/main/java/com/example/dnd_13th_9_be/folder/persistence/FolderRepositoryImpl.java
  src/main/java/com/example/dnd_13th_9_be/folder/persistence/adapter/FolderCommandAdapter.java
  src/main/java/com/example/dnd_13th_9_be/folder/persistence/adapter/FolderQueryAdapter.java
  src/main/java/com/example/dnd_13th_9_be/folder/persistence/adapter/PlanAccessAdapter.java
  src/main/java/com/example/dnd_13th_9_be/folder/persistence/dto/FolderSummary.java
  src/main/java/com/example/dnd_13th_9_be/folder/presentation/FolderController.java
  src/main/java/com/example/dnd_13th_9_be/folder/presentation/dto/request/CreateFolderRequest.java
  src/main/java/com/example/dnd_13th_9_be/folder/presentation/dto/request/RenameFolderRequest.java
  src/main/java/com/example/dnd_13th_9_be/folder/presentation/dto/response/FolderDetailResponse.java
  src/main/java/com/example/dnd_13th_9_be/folder/presentation/dto/response/FolderSummaryResponse.java
  src/main/java/com/example/dnd_13th_9_be/global/converter/BooleanAttributeConverter.java
  src/main/java/com/example/dnd_13th_9_be/global/error/ErrorCode.java
  src/main/java/com/example/dnd_13th_9_be/global/error/GlobalExceptionHandler.java
  src/main/java/com/example/dnd_13th_9_be/location/persistence/LocationImageEntity.java
  src/main/java/com/example/dnd_13th_9_be/location/persistence/LocationRecordEntity.java
  src/main/java/com/example/dnd_13th_9_be/plan/application/PlanService.java
  src/main/java/com/example/dnd_13th_9_be/plan/application/dto/PlanDetailResult.java
  src/main/java/com/example/dnd_13th_9_be/plan/application/dto/PlanSummaryResult.java
  src/main/java/com/example/dnd_13th_9_be/plan/application/port/PlanCommandPort.java
  src/main/java/com/example/dnd_13th_9_be/plan/application/port/PlanQueryPort.java
  src/main/java/com/example/dnd_13th_9_be/plan/application/port/UserAccessPort.java
  src/main/java/com/example/dnd_13th_9_be/plan/persistence/PlanRepository.java
  src/main/java/com/example/dnd_13th_9_be/plan/persistence/PlanRepositoryCustom.java
  src/main/java/com/example/dnd_13th_9_be/plan/persistence/PlanRepositoryImpl.java
  src/main/java/com/example/dnd_13th_9_be/plan/persistence/adapter/PlanCommandAdapter.java
  src/main/java/com/example/dnd_13th_9_be/plan/persistence/adapter/PlanQueryAdapter.java
  src/main/java/com/example/dnd_13th_9_be/plan/persistence/adapter/UserAccessAdapter.java
  src/main/java/com/example/dnd_13th_9_be/plan/persistence/dto/PlanSummary.java
  src/main/java/com/example/dnd_13th_9_be/plan/persistence/entity/PlanEntity.java
  src/main/java/com/example/dnd_13th_9_be/plan/presentation/PlanController.java
  src/main/java/com/example/dnd_13th_9_be/plan/presentation/dto/request/CreatePlanRequest.java
  src/main/java/com/example/dnd_13th_9_be/plan/presentation/dto/request/RenamePlanRequest.java
  src/main/java/com/example/dnd_13th_9_be/plan/presentation/dto/response/PlanDetailResponse.java
  src/main/java/com/example/dnd_13th_9_be/plan/presentation/dto/response/PlanSummaryResponse.java
  src/main/java/com/example/dnd_13th_9_be/property/persistence/PropertyImageEntity.java
  src/main/java/com/example/dnd_13th_9_be/property/persistence/PropertyRecordEntity.java
  src/main/java/com/example/dnd_13th_9_be/property/persistence/PropertyTransportEntity.java
  src/main/java/com/example/dnd_13th_9_be/user/persistence/UserEntity.java
  src/main/java/com/example/dnd_13th_9_be/user/persistence/UserRepository.java
  src/main/resources/application-prod.yml
Labels: FEAT

#23 feat : 카카오 로그인 및 security, jwt 구현
  build.gradle
  src/main/java/com/example/dnd_13th_9_be/checklist/persistence/UserChecklistFavoriteEntity.java
  src/main/java/com/example/dnd_13th_9_be/common/persistence/BaseEntity.java
  src/main/java/com/example/dnd_13th_9_be/common/support/AbstractModel.java
  src/main/java/com/example/dnd_13th_9_be/common/support/converter/AbstractEntityConverter.java
  src/main/java/com/example/dnd_13th_9_be/common/utils/CookieUtil.java
  src/main/java/com/example/dnd_13th_9_be/common/utils/JWTUtil.java
  src/main/java/com/example/dnd_13th_9_be/common/utils/SecurityUtil.java
  src/main/java/com/example/dnd_13th_9_be/config/AppProperties.java
  src/main/java/com/example/dnd_13th_9_be/config/WebConfig.java
  src/main/java/com/example/dnd_13th_9_be/config/security/CustomAccessDeniedHandler.java
  src/main/java/com/example/dnd_13th_9_be/config/security/CustomAuthenticationEntryPoint.java
  src/main/java/com/example/dnd_13th_9_be/config/security/CustomSuccessHandler.java
  src/main/java/com/example/dnd_13th_9_be/config/security/JWTFilter.java
  src/main/java/com/example/dnd_13th_9_be/config/security/SecurityConfig.java
  src/main/java/com/example/dnd_13th_9_be/global/error/ErrorCode.java
  src/main/java/com/example/dnd_13th_9_be/global/error/InvalidTokenException.java
  src/main/java/com/example/dnd_13th_9_be/global/error/JwtAuthenticationException.java
  src/main/java/com/example/dnd_13th_9_be/global/error/UserNotFoundException.java
  src/main/java/com/example/dnd_13th_9_be/plan/application/PlanService.java
  src/main/java/com/example/dnd_13th_9_be/plan/application/port/UserAccessPort.java
  src/main/java/com/example/dnd_13th_9_be/plan/persistence/adapter/PlanCommandAdapter.java
  src/main/java/com/example/dnd_13th_9_be/plan/persistence/adapter/UserAccessAdapter.java
  src/main/java/com/example/dnd_13th_9_be/plan/persistence/entity/PlanEntity.java
  src/main/java/com/example/dnd_13th_9_be/user/application/dto/KakaoAttribute.java
  src/main/java/com/example/dnd_13th_9_be/user/application/dto/OAuth2Attribute.java
  src/main/java/com/example/dnd_13th_9_be/user/application/dto/RoleAttribute.java
  src/main/java/com/example/dnd_13th_9_be/user/application/dto/TokenRefreshResponseDto.java
  src/main/java/com/example/dnd_13th_9_be/user/application/dto/UserPrincipalDto.java
  src/main/java/com/example/dnd_13th_9_be/user/application/dto/UserResponseDto.java
  src/main/java/com/example/dnd_13th_9_be/user/application/model/RefreshTokenModel.java
  src/main/java/com/example/dnd_13th_9_be/user/application/model/UserModel.java
  src/main/java/com/example/dnd_13th_9_be/user/application/model/converter/RefreshTokenConverter.java
  src/main/java/com/example/dnd_13th_9_be/user/application/model/converter/UserConverter.java
  src/main/java/com/example/dnd_13th_9_be/user/application/repository/RefreshTokenRepository.java
  src/main/java/com/example/dnd_13th_9_be/user/application/repository/UserRepository.java
  src/main/java/com/example/dnd_13th_9_be/user/application/service/CustomOauth2UserService.java
  src/main/java/com/example/dnd_13th_9_be/user/application/service/UserService.java
  src/main/java/com/example/dnd_13th_9_be/user/application/token/AuthService.java
  src/main/java/com/example/dnd_13th_9_be/user/application/token/CookieService.java
  src/main/java/com/example/dnd_13th_9_be/user/application/token/JwtTokenValidatorService.java
  src/main/java/com/example/dnd_13th_9_be/user/application/token/RefreshTokenService.java
  src/main/java/com/example/dnd_13th_9_be/user/persistence/JpaRefreshTokenRepository.java
  src/main/java/com/example/dnd_13th_9_be/user/persistence/JpaUserRepository.java
  src/main/java/com/example/dnd_13th_9_be/user/persistence/RefreshToken.java
  src/main/java/com/example/dnd_13th_9_be/user/persistence/RefreshTokenRepositoryImpl.java
  src/main/java/com/example/dnd_13th_9_be/user/persistence/User.java
  src/main/java/com/example/dnd_13th_9_be/user/persistence/UserEntity.java
  src/main/java/com/example/dnd_13th_9_be/user/persistence/UserRepository.java
  src/main/java/com/example/dnd_13th_9_be/user/persistence/UserRepositoryImpl.java
  src/main/java/com/example/dnd_13th_9_be/user/presentation/UserController.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: FEAT

#31 [FEAT] 사용자 생성시 기본 폴더, 기본 계획 생성
  src/main/java/com/example/dnd_13th_9_be/folder/application/FolderService.java
  src/main/java/com/example/dnd_13th_9_be/plan/application/PlanService.java
  src/main/java/com/example/dnd_13th_9_be/user/application/service/CustomOauth2UserService.java
Labels: FEAT

#35 [REFACTOR] Plan, Folder 도메인 Converter 아키텍처로 리팩토링
  src/main/java/com/example/dnd_13th_9_be/config/security/SecurityConfig.java
  src/main/java/com/example/dnd_13th_9_be/folder/application/FolderService.java
  src/main/java/com/example/dnd_13th_9_be/folder/application/port/FolderCommandPort.java
  src/main/java/com/example/dnd_13th_9_be/folder/application/port/FolderQueryPort.java
  src/main/java/com/example/dnd_13th_9_be/folder/application/port/PlanAccessPort.java
  src/main/java/com/example/dnd_13th_9_be/folder/application/repository/FolderRepository.java
  src/main/java/com/example/dnd_13th_9_be/folder/persistence/FolderRepository.java
  src/main/java/com/example/dnd_13th_9_be/folder/persistence/FolderRepositoryCustom.java
  src/main/java/com/example/dnd_13th_9_be/folder/persistence/FolderRepositoryImpl.java
  src/main/java/com/example/dnd_13th_9_be/folder/persistence/JpaFolderRepository.java
  src/main/java/com/example/dnd_13th_9_be/folder/persistence/QueryDslFolderRepository.java
  src/main/java/com/example/dnd_13th_9_be/folder/persistence/QueryDslFolderRepositoryImpl.java
  src/main/java/com/example/dnd_13th_9_be/folder/persistence/adapter/FolderCommandAdapter.java
  src/main/java/com/example/dnd_13th_9_be/folder/persistence/adapter/FolderQueryAdapter.java
  src/main/java/com/example/dnd_13th_9_be/folder/persistence/adapter/PlanAccessAdapter.java
  src/main/java/com/example/dnd_13th_9_be/folder/persistence/dto/FolderSummary.java
  src/main/java/com/example/dnd_13th_9_be/folder/persistence/entity/Folder.java
  src/main/java/com/example/dnd_13th_9_be/folder/presentation/FolderController.java
  src/main/java/com/example/dnd_13th_9_be/folder/presentation/docs/FolderDocs.java
  src/main/java/com/example/dnd_13th_9_be/folder/presentation/dto/request/CreateFolderRequest.java
  src/main/java/com/example/dnd_13th_9_be/folder/presentation/dto/request/RenameFolderRequest.java
  src/main/java/com/example/dnd_13th_9_be/folder/presentation/dto/response/FolderDetailResponse.java
  src/main/java/com/example/dnd_13th_9_be/folder/presentation/dto/response/FolderSummaryResponse.java
  src/main/java/com/example/dnd_13th_9_be/location/persistence/LocationRecordEntity.java
  src/main/java/com/example/dnd_13th_9_be/plan/application/PlanService.java
  src/main/java/com/example/dnd_13th_9_be/plan/application/port/PlanCommandPort.java
  src/main/java/com/example/dnd_13th_9_be/plan/application/port/PlanQueryPort.java
  src/main/java/com/example/dnd_13th_9_be/plan/application/repository/PlanRepository.java
  src/main/java/com/example/dnd_13th_9_be/plan/persistence/JpaPlanRepository.java
  src/main/java/com/example/dnd_13th_9_be/plan/persistence/PlanRepository.java
  src/main/java/com/example/dnd_13th_9_be/plan/persistence/PlanRepositoryImpl.java
  src/main/java/com/example/dnd_13th_9_be/plan/persistence/QueryDslPlanRepository.java
  src/main/java/com/example/dnd_13th_9_be/plan/persistence/QueryDslPlanRepositoryImpl.java
  src/main/java/com/example/dnd_13th_9_be/plan/persistence/adapter/PlanCommandAdapter.java
  src/main/java/com/example/dnd_13th_9_be/plan/persistence/adapter/PlanQueryAdapter.java
  src/main/java/com/example/dnd_13th_9_be/plan/persistence/dto/PlanSummary.java
  src/main/java/com/example/dnd_13th_9_be/plan/persistence/entity/Plan.java
  src/main/java/com/example/dnd_13th_9_be/plan/presentation/PlanController.java
  src/main/java/com/example/dnd_13th_9_be/plan/presentation/docs/PlanDocs.java
  src/main/java/com/example/dnd_13th_9_be/plan/presentation/dto/request/CreatePlanRequest.java
  src/main/java/com/example/dnd_13th_9_be/plan/presentation/dto/request/RenamePlanRequest.java
  src/main/java/com/example/dnd_13th_9_be/plan/presentation/dto/response/PlanDetailResponse.java
  src/main/java/com/example/dnd_13th_9_be/plan/presentation/dto/response/PlanSummaryResponse.java
  src/main/java/com/example/dnd_13th_9_be/property/persistence/PropertyRecordEntity.java
Labels: REFACTOR

#36 [REFACTOR] CustomOAuth2UserService folder, plan 생성 의존성 분리 및 이벤트 기반 리팩토링
  src/main/java/com/example/dnd_13th_9_be/Dnd13th9BeApplication.java
  src/main/java/com/example/dnd_13th_9_be/common/event/UserCreatedEvent.java
  src/main/java/com/example/dnd_13th_9_be/common/event/UserDefaultResourceHandler.java
  src/main/java/com/example/dnd_13th_9_be/global/error/ErrorCode.java
  src/main/java/com/example/dnd_13th_9_be/user/application/service/CustomOauth2UserService.java
Labels: FEAT

#37 [FIX] 배포전 에러 수정
  src/main/java/com/example/dnd_13th_9_be/global/error/ErrorCode.java
  src/main/resources/application-prod.yml
Labels: FEAT

#56 [FEAT] 주변장소메모 생성, 수정, 삭제, 단건조회, 리스트 조회 구현
  src/main/java/com/example/dnd_13th_9_be/global/error/ErrorCode.java
  src/main/java/com/example/dnd_13th_9_be/placeMemo/application/dto/CreatePlaceMemoRequest.java
  src/main/java/com/example/dnd_13th_9_be/placeMemo/application/dto/CreatePlaceMemoResponse.java
  src/main/java/com/example/dnd_13th_9_be/placeMemo/application/dto/QueryPlaceMemoListResponse.java
  src/main/java/com/example/dnd_13th_9_be/placeMemo/application/dto/QueryPlaceMemoResponse.java
  src/main/java/com/example/dnd_13th_9_be/placeMemo/application/dto/UpdatePlaceMemoRequest.java
  src/main/java/com/example/dnd_13th_9_be/placeMemo/application/model/PlaceMemoModel.java
  src/main/java/com/example/dnd_13th_9_be/placeMemo/application/model/converter/PlaceMemoRequestConverter.java
  src/main/java/com/example/dnd_13th_9_be/placeMemo/application/repository/PlaceMemoRepository.java
  src/main/java/com/example/dnd_13th_9_be/placeMemo/application/service/PlaceMemoService.java
  src/main/java/com/example/dnd_13th_9_be/placeMemo/persistence/JpaPlaceMemoRepository.java
  src/main/java/com/example/dnd_13th_9_be/placeMemo/persistence/PlaceMemo.java
  src/main/java/com/example/dnd_13th_9_be/placeMemo/persistence/PlaceMemoImage.java
  src/main/java/com/example/dnd_13th_9_be/placeMemo/persistence/PlaceMemoRepositoryImpl.java
  src/main/java/com/example/dnd_13th_9_be/placeMemo/persistence/PlaceTag.java
  src/main/java/com/example/dnd_13th_9_be/placeMemo/persistence/converter/PlaceMemoConverter.java
  src/main/java/com/example/dnd_13th_9_be/placeMemo/presentation/PlaceMemoController.java
  src/main/java/com/example/dnd_13th_9_be/placeMemo/presentation/docs/PlaceMemoDocs.java
Labels: FEAT

#64 [feat] 마이페이지 UI 구성 API
  src/main/java/com/example/dnd_13th_9_be/checklist/application/repository/UserRequiredItemRepository.java
  src/main/java/com/example/dnd_13th_9_be/checklist/persistence/UserRequiredItemRepositoryImpl.java
  src/main/java/com/example/dnd_13th_9_be/property/application/repository/PropertyRepository.java
  src/main/java/com/example/dnd_13th_9_be/property/persistence/PropertyRepositoryImpl.java
  src/main/java/com/example/dnd_13th_9_be/user/application/dto/MyPageDto.java
  src/main/java/com/example/dnd_13th_9_be/user/application/service/MyPageService.java
  src/main/java/com/example/dnd_13th_9_be/user/presentation/MyPageController.java
  src/main/java/com/example/dnd_13th_9_be/user/presentation/docs/MyPageDocs.java
Labels: FEAT

#65 [FEATT] 매물 메모, 주변장소 메모 전체 리스트 조회
  src/main/java/com/example/dnd_13th_9_be/folder/application/FolderService.java
  src/main/java/com/example/dnd_13th_9_be/folder/presentation/FolderController.java
  src/main/java/com/example/dnd_13th_9_be/folder/presentation/docs/FolderDocs.java
  src/main/java/com/example/dnd_13th_9_be/folder/presentation/dto/response/QueryFolderMemoListResponse.java
Labels: FEAT

#69 [FIX] 매물메모, 주변장소 메모 전체 조회 응답값 통일
  src/main/java/com/example/dnd_13th_9_be/folder/application/dto/RecordSummaryResult.java
  src/main/java/com/example/dnd_13th_9_be/folder/presentation/docs/FolderDocs.java
  src/main/java/com/example/dnd_13th_9_be/folder/presentation/dto/response/RecordSummaryResponse.java
Labels: FIX

#70 [FIX] 매물메모, 주변장소 메모 전체조회 응답값 수정
  src/main/java/com/example/dnd_13th_9_be/folder/application/dto/RecordSummaryResult.java
  src/main/java/com/example/dnd_13th_9_be/folder/presentation/docs/FolderDocs.java
  src/main/java/com/example/dnd_13th_9_be/folder/presentation/dto/response/RecordSummaryResponse.java
Labels: RELEASE

#74 [REFACTOR] 주변장소메모 조회시 응답값 필드 추가 수정
  src/main/java/com/example/dnd_13th_9_be/placeMemo/application/dto/QueryPlaceMemoResponse.java
  src/main/java/com/example/dnd_13th_9_be/placeMemo/application/model/PlaceMemoModel.java
  src/main/java/com/example/dnd_13th_9_be/placeMemo/persistence/converter/PlaceMemoConverter.java
Labels: RELEASE

#75 [BUG] 매물 메모 API 이슈 수정
  src/main/java/com/example/dnd_13th_9_be/property/application/PropertyService.java
  src/main/java/com/example/dnd_13th_9_be/property/application/model/PropertyModel.java
  src/main/java/com/example/dnd_13th_9_be/property/persistence/PropertyRepositoryImpl.java
  src/main/java/com/example/dnd_13th_9_be/property/persistence/entity/Property.java
  src/main/java/com/example/dnd_13th_9_be/property/presentation/PropertyController.java
  src/main/java/com/example/dnd_13th_9_be/property/presentation/docs/PropertyDocs.java
  src/main/java/com/example/dnd_13th_9_be/property/presentation/dto/request/UpsertPropertyRequest.java
  src/main/java/com/example/dnd_13th_9_be/property/presentation/dto/response/PropertyCreateResponse.java
Labels: BUG

#81 [FEAT] 매물 메모 공유하기 기능 구현
  src/main/java/com/example/dnd_13th_9_be/common/cipher/AESCipherUtil.java
  src/main/java/com/example/dnd_13th_9_be/common/cipher/CipherUtil.java
  src/main/java/com/example/dnd_13th_9_be/common/utils/JsonUtil.java
  src/main/java/com/example/dnd_13th_9_be/config/security/JWTFilter.java
  src/main/java/com/example/dnd_13th_9_be/config/security/SecurityConfig.java
  src/main/java/com/example/dnd_13th_9_be/global/error/ErrorCode.java
  src/main/java/com/example/dnd_13th_9_be/property/presentation/PropertyController.java
  src/main/java/com/example/dnd_13th_9_be/property/presentation/PropertyShareController.java
  src/main/java/com/example/dnd_13th_9_be/property/presentation/docs/PropertyDocs.java
  src/main/java/com/example/dnd_13th_9_be/property/presentation/docs/PropertyShareDocs.java
  src/main/java/com/example/dnd_13th_9_be/property/presentation/dto/request/SharePropertyRequest.java
  src/main/java/com/example/dnd_13th_9_be/property/presentation/dto/response/SharePropertyResponse.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: FEAT

#83 [FIX] 체크리스트 목록 API
  src/main/java/com/example/dnd_13th_9_be/checklist/presentation/dto/ChecklistResponse.java
  src/main/java/com/example/dnd_13th_9_be/checklist/presentation/dto/SectionItem.java
  src/main/java/com/example/dnd_13th_9_be/property/presentation/PropertyShareController.java
  src/main/java/com/example/dnd_13th_9_be/property/presentation/docs/PropertyDocs.java
  src/main/java/com/example/dnd_13th_9_be/property/presentation/docs/PropertyShareDocs.java
Labels: BUG
